chore(setup): update docker install script, Makefile and Vagrant VM name

diff --git a/p3/Makefile b/p3/Makefile
--- a/p3/Makefile
+++ b/p3/Makefile
@@ -4,6 +4,13 @@ install: docker k3d kubectl
 
 docker:
 	@bash scripts/install/install_docker.sh
+	@status=$$?; \
+	if [ $$status -eq 1 ]; then \
+		echo ""; \
+		echo "Session restart required."; \
+		echo "Run make again after reconnecting."; \
+		exit 1; \
+	fi
 
 k3d:
 	@bash scripts/install/install_k3d.sh
